<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="0">
  <listeners>
    <listener class-name="RahulShettyAcademy.data.listenrers"/>
  </listeners>
  <test thread-count="5" parallel="tests" name="Sumit Order(failed)" verbose="0">
    <classes>
      <class name="RahulShettyAcademy.Tests.StandAloneTest">
        <methods>
          <include name="tearDown"/>
          <include name="launchApplication"/>
          <include name="FirstTest" invocation-numbers="0"/>
          <include name="orderHistoryTest"/>
        </methods>
      </class> <!-- RahulShettyAcademy.Tests.StandAloneTest -->
    </classes>
  </test> <!-- Sumit Order(failed) -->
  <test thread-count="5" parallel="tests" name="error validation test(failed)" verbose="0">
    <classes>
      <class name="RahulShettyAcademy.Tests.errorValidation">
        <methods>
          <include name="errorMessagetest"/>
          <include name="tearDown"/>
          <include name="launchApplication"/>
          <include name="WrongProduct"/>
        </methods>
      </class> <!-- RahulShettyAcademy.Tests.errorValidation -->
    </classes>
  </test> <!-- error validation test(failed) -->
</suite> <!-- Failed suite [Suite] -->
